# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.sub_account_identifier import SubAccountIdentifier


class AccountIdentifier(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccountIdentifier - a model defined in OpenAPI

        address: The address of this AccountIdentifier.
        sub_account: The sub_account of this AccountIdentifier [Optional].
        metadata: The metadata of this AccountIdentifier [Optional].
    """

    address: str
    sub_account: Optional[SubAccountIdentifier] = None
    metadata: Optional[Dict[str, Any]] = None

AccountIdentifier.update_forward_refs()
