# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.amount import Amount
from openapi_server.models.block_identifier import BlockIdentifier


class AccountBalanceResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccountBalanceResponse - a model defined in OpenAPI

        block_identifier: The block_identifier of this AccountBalanceResponse.
        balances: The balances of this AccountBalanceResponse.
        metadata: The metadata of this AccountBalanceResponse [Optional].
    """

    block_identifier: BlockIdentifier
    balances: List[Amount]
    metadata: Optional[Dict[str, Any]] = None

AccountBalanceResponse.update_forward_refs()
