# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier
from openapi_server.models.currency import Currency
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.partial_block_identifier import PartialBlockIdentifier


class AccountBalanceRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccountBalanceRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this AccountBalanceRequest.
        account_identifier: The account_identifier of this AccountBalanceRequest.
        block_identifier: The block_identifier of this AccountBalanceRequest [Optional].
        currencies: The currencies of this AccountBalanceRequest [Optional].
    """

    network_identifier: NetworkIdentifier
    account_identifier: AccountIdentifier
    block_identifier: Optional[PartialBlockIdentifier] = None
    currencies: Optional[List[Currency]] = None

AccountBalanceRequest.update_forward_refs()
