# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block_identifier import BlockIdentifier
from openapi_server.models.coin import Coin


class AccountCoinsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccountCoinsResponse - a model defined in OpenAPI

        block_identifier: The block_identifier of this AccountCoinsResponse.
        coins: The coins of this AccountCoinsResponse.
        metadata: The metadata of this AccountCoinsResponse [Optional].
    """

    block_identifier: BlockIdentifier
    coins: List[Coin]
    metadata: Optional[Dict[str, Any]] = None

AccountCoinsResponse.update_forward_refs()
