# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier
from openapi_server.models.currency import Currency
from openapi_server.models.network_identifier import NetworkIdentifier


class AccountCoinsRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccountCoinsRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this AccountCoinsRequest.
        account_identifier: The account_identifier of this AccountCoinsRequest.
        include_mempool: The include_mempool of this AccountCoinsRequest.
        currencies: The currencies of this AccountCoinsRequest [Optional].
    """

    network_identifier: NetworkIdentifier
    account_identifier: AccountIdentifier
    include_mempool: bool
    currencies: Optional[List[Currency]] = None

AccountCoinsRequest.update_forward_refs()
