# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Allow(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Allow - a model defined in OpenAPI

        operation_statuses: The operation_statuses of this Allow.
        operation_types: The operation_types of this Allow.
        errors: The errors of this Allow.
        historical_balance_lookup: The historical_balance_lookup of this Allow.
        timestamp_start_index: The timestamp_start_index of this Allow [Optional].
        call_methods: The call_methods of this Allow.
        balance_exemptions: The balance_exemptions of this Allow.
        mempool_coins: The mempool_coins of this Allow.
    """

    operation_statuses: List[object]
    operation_types: List[str]
    errors: List[object]
    historical_balance_lookup: bool
    timestamp_start_index: Optional[int] = None
    call_methods: List[str]
    balance_exemptions: List[object]
    mempool_coins: bool

    @validator("timestamp_start_index")
    def timestamp_start_index_min(cls, value):
        assert value >= 0
        return value

Allow.update_forward_refs()
