# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.currency import Currency


class Amount(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Amount - a model defined in OpenAPI

        value: The value of this Amount.
        currency: The currency of this Amount.
        metadata: The metadata of this Amount [Optional].
    """

    value: str
    currency: Currency
    metadata: Optional[Dict[str, Any]] = None

Amount.update_forward_refs()
