# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.currency import Currency
from openapi_server.models.exemption_type import ExemptionType


class BalanceExemption(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BalanceExemption - a model defined in OpenAPI

        sub_account_address: The sub_account_address of this BalanceExemption [Optional].
        currency: The currency of this BalanceExemption [Optional].
        exemption_type: The exemption_type of this BalanceExemption [Optional].
    """

    sub_account_address: Optional[str] = None
    currency: Optional[Currency] = None
    exemption_type: Optional[ExemptionType] = None

BalanceExemption.update_forward_refs()
