# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block_identifier import BlockIdentifier
from openapi_server.models.transaction import Transaction


class Block(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Block - a model defined in OpenAPI

        block_identifier: The block_identifier of this Block.
        parent_block_identifier: The parent_block_identifier of this Block.
        timestamp: The timestamp of this Block.
        transactions: The transactions of this Block.
        metadata: The metadata of this Block [Optional].
    """

    block_identifier: BlockIdentifier
    parent_block_identifier: BlockIdentifier
    timestamp: int
    transactions: List[Transaction]
    metadata: Optional[Dict[str, Any]] = None

    @validator("timestamp")
    def timestamp_min(cls, value):
        assert value >= 0
        return value

Block.update_forward_refs()
