# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block_event_type import BlockEventType
from openapi_server.models.block_identifier import BlockIdentifier


class BlockEvent(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BlockEvent - a model defined in OpenAPI

        sequence: The sequence of this BlockEvent.
        block_identifier: The block_identifier of this BlockEvent.
        type: The type of this BlockEvent.
    """

    sequence: int
    block_identifier: BlockIdentifier
    type: BlockEventType

    @validator("sequence")
    def sequence_min(cls, value):
        assert value >= 0
        return value

BlockEvent.update_forward_refs()
