# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block import Block
from openapi_server.models.transaction_identifier import TransactionIdentifier


class BlockResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BlockResponse - a model defined in OpenAPI

        block: The block of this BlockResponse [Optional].
        other_transactions: The other_transactions of this BlockResponse [Optional].
    """

    block: Optional[Block] = None
    other_transactions: Optional[List[TransactionIdentifier]] = None

BlockResponse.update_forward_refs()
