# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class BlockIdentifier(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BlockIdentifier - a model defined in OpenAPI

        index: The index of this BlockIdentifier.
        hash: The hash of this BlockIdentifier.
    """

    index: int
    hash: str

BlockIdentifier.update_forward_refs()
