# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block_identifier import BlockIdentifier
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.transaction_identifier import TransactionIdentifier


class BlockTransactionRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BlockTransactionRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this BlockTransactionRequest.
        block_identifier: The block_identifier of this BlockTransactionRequest.
        transaction_identifier: The transaction_identifier of this BlockTransactionRequest.
    """

    network_identifier: NetworkIdentifier
    block_identifier: BlockIdentifier
    transaction_identifier: TransactionIdentifier

BlockTransactionRequest.update_forward_refs()
