# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class CallResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CallResponse - a model defined in OpenAPI

        result: The result of this CallResponse.
        idempotent: The idempotent of this CallResponse.
    """

    result: Dict[str, Any]
    idempotent: bool

CallResponse.update_forward_refs()
