# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.amount import Amount
from openapi_server.models.coin_identifier import CoinIdentifier


class Coin(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Coin - a model defined in OpenAPI

        coin_identifier: The coin_identifier of this Coin.
        amount: The amount of this Coin.
    """

    coin_identifier: CoinIdentifier
    amount: Amount

Coin.update_forward_refs()
