# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.coin_action import CoinAction
from openapi_server.models.coin_identifier import CoinIdentifier


class CoinChange(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CoinChange - a model defined in OpenAPI

        coin_identifier: The coin_identifier of this CoinChange.
        coin_action: The coin_action of this CoinChange.
    """

    coin_identifier: CoinIdentifier
    coin_action: CoinAction

CoinChange.update_forward_refs()
