# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.public_key import PublicKey


class ConstructionMetadataRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionMetadataRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this ConstructionMetadataRequest.
        options: The options of this ConstructionMetadataRequest [Optional].
        public_keys: The public_keys of this ConstructionMetadataRequest [Optional].
    """

    network_identifier: NetworkIdentifier
    options: Optional[Dict[str, Any]] = None
    public_keys: Optional[List[PublicKey]] = None

ConstructionMetadataRequest.update_forward_refs()
