# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier


class ConstructionPreprocessResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionPreprocessResponse - a model defined in OpenAPI

        options: The options of this ConstructionPreprocessResponse [Optional].
        required_public_keys: The required_public_keys of this ConstructionPreprocessResponse [Optional].
    """

    options: Optional[Dict[str, Any]] = None
    required_public_keys: Optional[List[AccountIdentifier]] = None

ConstructionPreprocessResponse.update_forward_refs()
