# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier
from openapi_server.models.operation import Operation


class ConstructionParseResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionParseResponse - a model defined in OpenAPI

        operations: The operations of this ConstructionParseResponse.
        signers: The signers of this ConstructionParseResponse [Optional].
        account_identifier_signers: The account_identifier_signers of this ConstructionParseResponse [Optional].
        metadata: The metadata of this ConstructionParseResponse [Optional].
    """

    operations: List[Operation]
    signers: Optional[List[str]] = None
    account_identifier_signers: Optional[List[AccountIdentifier]] = None
    metadata: Optional[Dict[str, Any]] = None

ConstructionParseResponse.update_forward_refs()
