# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.amount import Amount
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.operation import Operation


class ConstructionPreprocessRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionPreprocessRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this ConstructionPreprocessRequest.
        operations: The operations of this ConstructionPreprocessRequest.
        metadata: The metadata of this ConstructionPreprocessRequest [Optional].
        max_fee: The max_fee of this ConstructionPreprocessRequest [Optional].
        suggested_fee_multiplier: The suggested_fee_multiplier of this ConstructionPreprocessRequest [Optional].
    """

    network_identifier: NetworkIdentifier
    operations: List[Operation]
    metadata: Optional[Dict[str, Any]] = None
    max_fee: Optional[List[Amount]] = None
    suggested_fee_multiplier: Optional[float] = None

    @validator("suggested_fee_multiplier")
    def suggested_fee_multiplier_min(cls, value):
        assert value >= 0.0
        return value

ConstructionPreprocessRequest.update_forward_refs()
