# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.operation import Operation
from openapi_server.models.public_key import PublicKey


class ConstructionPayloadsRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionPayloadsRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this ConstructionPayloadsRequest.
        operations: The operations of this ConstructionPayloadsRequest.
        metadata: The metadata of this ConstructionPayloadsRequest [Optional].
        public_keys: The public_keys of this ConstructionPayloadsRequest [Optional].
    """

    network_identifier: NetworkIdentifier
    operations: List[Operation]
    metadata: Optional[Dict[str, Any]] = None
    public_keys: Optional[List[PublicKey]] = None

ConstructionPayloadsRequest.update_forward_refs()
