# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.amount import Amount


class ConstructionMetadataResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionMetadataResponse - a model defined in OpenAPI

        metadata: The metadata of this ConstructionMetadataResponse.
        suggested_fee: The suggested_fee of this ConstructionMetadataResponse [Optional].
    """

    metadata: Dict[str, Any]
    suggested_fee: Optional[List[Amount]] = None

ConstructionMetadataResponse.update_forward_refs()
