# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.public_key import PublicKey


class ConstructionDeriveRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionDeriveRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this ConstructionDeriveRequest.
        public_key: The public_key of this ConstructionDeriveRequest.
        metadata: The metadata of this ConstructionDeriveRequest [Optional].
    """

    network_identifier: NetworkIdentifier
    public_key: PublicKey
    metadata: Optional[Dict[str, Any]] = None

ConstructionDeriveRequest.update_forward_refs()
