# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier


class ConstructionSubmitRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionSubmitRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this ConstructionSubmitRequest.
        signed_transaction: The signed_transaction of this ConstructionSubmitRequest.
    """

    network_identifier: NetworkIdentifier
    signed_transaction: str

ConstructionSubmitRequest.update_forward_refs()
