# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.signature import Signature


class ConstructionCombineRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionCombineRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this ConstructionCombineRequest.
        unsigned_transaction: The unsigned_transaction of this ConstructionCombineRequest.
        signatures: The signatures of this ConstructionCombineRequest.
    """

    network_identifier: NetworkIdentifier
    unsigned_transaction: str
    signatures: List[Signature]

ConstructionCombineRequest.update_forward_refs()
