# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier


class ConstructionParseRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionParseRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this ConstructionParseRequest.
        signed: The signed of this ConstructionParseRequest.
        transaction: The transaction of this ConstructionParseRequest.
    """

    network_identifier: NetworkIdentifier
    signed: bool
    transaction: str

ConstructionParseRequest.update_forward_refs()
