# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier


class ConstructionDeriveResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionDeriveResponse - a model defined in OpenAPI

        address: The address of this ConstructionDeriveResponse [Optional].
        account_identifier: The account_identifier of this ConstructionDeriveResponse [Optional].
        metadata: The metadata of this ConstructionDeriveResponse [Optional].
    """

    address: Optional[str] = None
    account_identifier: Optional[AccountIdentifier] = None
    metadata: Optional[Dict[str, Any]] = None

ConstructionDeriveResponse.update_forward_refs()
