# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.signing_payload import SigningPayload


class ConstructionPayloadsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstructionPayloadsResponse - a model defined in OpenAPI

        unsigned_transaction: The unsigned_transaction of this ConstructionPayloadsResponse.
        payloads: The payloads of this ConstructionPayloadsResponse.
    """

    unsigned_transaction: str
    payloads: List[SigningPayload]

ConstructionPayloadsResponse.update_forward_refs()
