# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Currency(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Currency - a model defined in OpenAPI

        symbol: The symbol of this Currency.
        decimals: The decimals of this Currency.
        metadata: The metadata of this Currency [Optional].
    """

    symbol: str
    decimals: int
    metadata: Optional[Dict[str, Any]] = None

    @validator("decimals")
    def decimals_min(cls, value):
        assert value >= 0
        return value

Currency.update_forward_refs()
