# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Error(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Error - a model defined in OpenAPI

        code: The code of this Error.
        message: The message of this Error.
        description: The description of this Error [Optional].
        retriable: The retriable of this Error.
        details: The details of this Error [Optional].
    """

    code: int
    message: str
    description: Optional[str] = None
    retriable: bool
    details: Optional[Dict[str, Any]] = None

    @validator("code")
    def code_min(cls, value):
        assert value >= 0
        return value

Error.update_forward_refs()
