# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block_event import BlockEvent


class EventsBlocksResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EventsBlocksResponse - a model defined in OpenAPI

        max_sequence: The max_sequence of this EventsBlocksResponse.
        events: The events of this EventsBlocksResponse.
    """

    max_sequence: int
    events: List[BlockEvent]

    @validator("max_sequence")
    def max_sequence_min(cls, value):
        assert value >= 0
        return value

EventsBlocksResponse.update_forward_refs()
