# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.transaction_identifier import TransactionIdentifier


class MempoolTransactionRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MempoolTransactionRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this MempoolTransactionRequest.
        transaction_identifier: The transaction_identifier of this MempoolTransactionRequest.
    """

    network_identifier: NetworkIdentifier
    transaction_identifier: TransactionIdentifier

MempoolTransactionRequest.update_forward_refs()
