# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.transaction import Transaction


class MempoolTransactionResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MempoolTransactionResponse - a model defined in OpenAPI

        transaction: The transaction of this MempoolTransactionResponse.
        metadata: The metadata of this MempoolTransactionResponse [Optional].
    """

    transaction: Transaction
    metadata: Optional[Dict[str, Any]] = None

MempoolTransactionResponse.update_forward_refs()
