# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block_identifier import BlockIdentifier
from openapi_server.models.peer import Peer
from openapi_server.models.sync_status import SyncStatus


class NetworkStatusResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NetworkStatusResponse - a model defined in OpenAPI

        current_block_identifier: The current_block_identifier of this NetworkStatusResponse.
        current_block_timestamp: The current_block_timestamp of this NetworkStatusResponse.
        genesis_block_identifier: The genesis_block_identifier of this NetworkStatusResponse.
        oldest_block_identifier: The oldest_block_identifier of this NetworkStatusResponse [Optional].
        sync_status: The sync_status of this NetworkStatusResponse [Optional].
        peers: The peers of this NetworkStatusResponse.
    """

    current_block_identifier: BlockIdentifier
    current_block_timestamp: int
    genesis_block_identifier: BlockIdentifier
    oldest_block_identifier: Optional[BlockIdentifier] = None
    sync_status: Optional[SyncStatus] = None
    peers: List[Peer]

    @validator("current_block_timestamp")
    def current_block_timestamp_min(cls, value):
        assert value >= 0
        return value

NetworkStatusResponse.update_forward_refs()
