# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.network_identifier import NetworkIdentifier


class NetworkListResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NetworkListResponse - a model defined in OpenAPI

        network_identifiers: The network_identifiers of this NetworkListResponse.
    """

    network_identifiers: List[NetworkIdentifier]

NetworkListResponse.update_forward_refs()
