# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.sub_network_identifier import SubNetworkIdentifier


class NetworkIdentifier(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NetworkIdentifier - a model defined in OpenAPI

        blockchain: The blockchain of this NetworkIdentifier.
        network: The network of this NetworkIdentifier.
        sub_network_identifier: The sub_network_identifier of this NetworkIdentifier [Optional].
    """

    blockchain: str
    network: str
    sub_network_identifier: Optional[SubNetworkIdentifier] = None

NetworkIdentifier.update_forward_refs()
