# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class OperationIdentifier(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OperationIdentifier - a model defined in OpenAPI

        index: The index of this OperationIdentifier.
        network_index: The network_index of this OperationIdentifier [Optional].
    """

    index: int
    network_index: Optional[int] = None

    @validator("index")
    def index_min(cls, value):
        assert value >= 0
        return value

    @validator("network_index")
    def network_index_min(cls, value):
        assert value >= 0
        return value

OperationIdentifier.update_forward_refs()
