# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier
from openapi_server.models.amount import Amount
from openapi_server.models.coin_change import CoinChange
from openapi_server.models.operation_identifier import OperationIdentifier


class Operation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Operation - a model defined in OpenAPI

        operation_identifier: The operation_identifier of this Operation.
        related_operations: The related_operations of this Operation [Optional].
        type: The type of this Operation.
        status: The status of this Operation [Optional].
        account: The account of this Operation [Optional].
        amount: The amount of this Operation [Optional].
        coin_change: The coin_change of this Operation [Optional].
        metadata: The metadata of this Operation [Optional].
    """

    operation_identifier: OperationIdentifier
    related_operations: Optional[List[OperationIdentifier]] = None
    type: str
    status: Optional[str] = None
    account: Optional[AccountIdentifier] = None
    amount: Optional[Amount] = None
    coin_change: Optional[CoinChange] = None
    metadata: Optional[Dict[str, Any]] = None

Operation.update_forward_refs()
