# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class OperationStatus(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OperationStatus - a model defined in OpenAPI

        status: The status of this OperationStatus.
        successful: The successful of this OperationStatus.
    """

    status: str
    successful: bool

OperationStatus.update_forward_refs()
