# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class PartialBlockIdentifier(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PartialBlockIdentifier - a model defined in OpenAPI

        index: The index of this PartialBlockIdentifier [Optional].
        hash: The hash of this PartialBlockIdentifier [Optional].
    """

    index: Optional[int] = None
    hash: Optional[str] = None

PartialBlockIdentifier.update_forward_refs()
