# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Peer(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Peer - a model defined in OpenAPI

        peer_id: The peer_id of this Peer.
        metadata: The metadata of this Peer [Optional].
    """

    peer_id: str
    metadata: Optional[Dict[str, Any]] = None

Peer.update_forward_refs()
