# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.curve_type import CurveType


class PublicKey(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PublicKey - a model defined in OpenAPI

        hex_bytes: The hex_bytes of this PublicKey.
        curve_type: The curve_type of this PublicKey.
    """

    hex_bytes: str
    curve_type: CurveType

PublicKey.update_forward_refs()
