# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.direction import Direction
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.transaction_identifier import TransactionIdentifier


class RelatedTransaction(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RelatedTransaction - a model defined in OpenAPI

        network_identifier: The network_identifier of this RelatedTransaction [Optional].
        transaction_identifier: The transaction_identifier of this RelatedTransaction.
        direction: The direction of this RelatedTransaction.
    """

    network_identifier: Optional[NetworkIdentifier] = None
    transaction_identifier: TransactionIdentifier
    direction: Direction

RelatedTransaction.update_forward_refs()
