# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier
from openapi_server.models.coin_identifier import CoinIdentifier
from openapi_server.models.currency import Currency
from openapi_server.models.network_identifier import NetworkIdentifier
from openapi_server.models.operator import Operator
from openapi_server.models.transaction_identifier import TransactionIdentifier


class SearchTransactionsRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SearchTransactionsRequest - a model defined in OpenAPI

        network_identifier: The network_identifier of this SearchTransactionsRequest.
        operator: The operator of this SearchTransactionsRequest [Optional].
        max_block: The max_block of this SearchTransactionsRequest [Optional].
        offset: The offset of this SearchTransactionsRequest [Optional].
        limit: The limit of this SearchTransactionsRequest [Optional].
        transaction_identifier: The transaction_identifier of this SearchTransactionsRequest [Optional].
        account_identifier: The account_identifier of this SearchTransactionsRequest [Optional].
        coin_identifier: The coin_identifier of this SearchTransactionsRequest [Optional].
        currency: The currency of this SearchTransactionsRequest [Optional].
        status: The status of this SearchTransactionsRequest [Optional].
        type: The type of this SearchTransactionsRequest [Optional].
        address: The address of this SearchTransactionsRequest [Optional].
        success: The success of this SearchTransactionsRequest [Optional].
    """

    network_identifier: NetworkIdentifier
    operator: Optional[Operator] = None
    max_block: Optional[int] = None
    offset: Optional[int] = None
    limit: Optional[int] = None
    transaction_identifier: Optional[TransactionIdentifier] = None
    account_identifier: Optional[AccountIdentifier] = None
    coin_identifier: Optional[CoinIdentifier] = None
    currency: Optional[Currency] = None
    status: Optional[str] = None
    type: Optional[str] = None
    address: Optional[str] = None
    success: Optional[bool] = None

    @validator("max_block")
    def max_block_min(cls, value):
        assert value >= 0
        return value

    @validator("offset")
    def offset_min(cls, value):
        assert value >= 0
        return value

    @validator("limit")
    def limit_min(cls, value):
        assert value >= 0
        return value

SearchTransactionsRequest.update_forward_refs()
