# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.block_transaction import BlockTransaction


class SearchTransactionsResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SearchTransactionsResponse - a model defined in OpenAPI

        transactions: The transactions of this SearchTransactionsResponse.
        total_count: The total_count of this SearchTransactionsResponse.
        next_offset: The next_offset of this SearchTransactionsResponse [Optional].
    """

    transactions: List[BlockTransaction]
    total_count: int
    next_offset: Optional[int] = None

    @validator("total_count")
    def total_count_min(cls, value):
        assert value >= 0
        return value

    @validator("next_offset")
    def next_offset_min(cls, value):
        assert value >= 0
        return value

SearchTransactionsResponse.update_forward_refs()
