# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.account_identifier import AccountIdentifier
from openapi_server.models.signature_type import SignatureType


class SigningPayload(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SigningPayload - a model defined in OpenAPI

        address: The address of this SigningPayload [Optional].
        account_identifier: The account_identifier of this SigningPayload [Optional].
        hex_bytes: The hex_bytes of this SigningPayload.
        signature_type: The signature_type of this SigningPayload [Optional].
    """

    address: Optional[str] = None
    account_identifier: Optional[AccountIdentifier] = None
    hex_bytes: str
    signature_type: Optional[SignatureType] = None

SigningPayload.update_forward_refs()
