# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.public_key import PublicKey
from openapi_server.models.signature_type import SignatureType
from openapi_server.models.signing_payload import SigningPayload


class Signature(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Signature - a model defined in OpenAPI

        signing_payload: The signing_payload of this Signature.
        public_key: The public_key of this Signature.
        signature_type: The signature_type of this Signature.
        hex_bytes: The hex_bytes of this Signature.
    """

    signing_payload: SigningPayload
    public_key: PublicKey
    signature_type: SignatureType
    hex_bytes: str

Signature.update_forward_refs()
