# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class SubAccountIdentifier(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SubAccountIdentifier - a model defined in OpenAPI

        address: The address of this SubAccountIdentifier.
        metadata: The metadata of this SubAccountIdentifier [Optional].
    """

    address: str
    metadata: Optional[Dict[str, Any]] = None

SubAccountIdentifier.update_forward_refs()
