# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class SubNetworkIdentifier(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SubNetworkIdentifier - a model defined in OpenAPI

        network: The network of this SubNetworkIdentifier.
        metadata: The metadata of this SubNetworkIdentifier [Optional].
    """

    network: str
    metadata: Optional[Dict[str, Any]] = None

SubNetworkIdentifier.update_forward_refs()
