# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class SyncStatus(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SyncStatus - a model defined in OpenAPI

        current_index: The current_index of this SyncStatus [Optional].
        target_index: The target_index of this SyncStatus [Optional].
        stage: The stage of this SyncStatus [Optional].
        synced: The synced of this SyncStatus [Optional].
    """

    current_index: Optional[int] = None
    target_index: Optional[int] = None
    stage: Optional[str] = None
    synced: Optional[bool] = None

SyncStatus.update_forward_refs()
