# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.operation import Operation
from openapi_server.models.related_transaction import RelatedTransaction
from openapi_server.models.transaction_identifier import TransactionIdentifier


class Transaction(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Transaction - a model defined in OpenAPI

        transaction_identifier: The transaction_identifier of this Transaction.
        operations: The operations of this Transaction.
        related_transactions: The related_transactions of this Transaction [Optional].
        metadata: The metadata of this Transaction [Optional].
    """

    transaction_identifier: TransactionIdentifier
    operations: List[Operation]
    related_transactions: Optional[List[RelatedTransaction]] = None
    metadata: Optional[Dict[str, Any]] = None

Transaction.update_forward_refs()
