# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.transaction_identifier import TransactionIdentifier


class TransactionIdentifierResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TransactionIdentifierResponse - a model defined in OpenAPI

        transaction_identifier: The transaction_identifier of this TransactionIdentifierResponse.
        metadata: The metadata of this TransactionIdentifierResponse [Optional].
    """

    transaction_identifier: TransactionIdentifier
    metadata: Optional[Dict[str, Any]] = None

TransactionIdentifierResponse.update_forward_refs()
