# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Version(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Version - a model defined in OpenAPI

        rosetta_version: The rosetta_version of this Version.
        node_version: The node_version of this Version.
        middleware_version: The middleware_version of this Version [Optional].
        metadata: The metadata of this Version [Optional].
    """

    rosetta_version: str
    node_version: str
    middleware_version: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None

Version.update_forward_refs()
