# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere. 

    The version of the OpenAPI document: 1.4.10
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.account_api import router as AccountApiRouter
from openapi_server.apis.block_api import router as BlockApiRouter
from openapi_server.apis.call_api import router as CallApiRouter
from openapi_server.apis.construction_api import router as ConstructionApiRouter
from openapi_server.apis.events_api import router as EventsApiRouter
from openapi_server.apis.mempool_api import router as MempoolApiRouter
from openapi_server.apis.network_api import router as NetworkApiRouter
from openapi_server.apis.search_api import router as SearchApiRouter

app = FastAPI(
    title="Rosetta",
    description="Build Once. Integrate Your Blockchain Everywhere. ",
    version="1.4.10",
)

app.include_router(AccountApiRouter)
app.include_router(BlockApiRouter)
app.include_router(CallApiRouter)
app.include_router(ConstructionApiRouter)
app.include_router(EventsApiRouter)
app.include_router(MempoolApiRouter)
app.include_router(NetworkApiRouter)
app.include_router(SearchApiRouter)
