/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockAtPublicRequestDTO, BlockAtPublicRequestDTOToJSON, BlockDTO, BlockDTOFromJSON } from '../models';
import * as runtime from '../runtime';

export interface BlockAtPublicRequest {
    blockAtPublicRequestDTO?: BlockAtPublicRequestDTO;
}

/**
 * BlockApi - interface
 *
 * @export
 * @interface BlockApiInterface
 */
export interface BlockApiInterface {
    /**
     * Gets a block from the chain that has the given height.
     * @summary Block at given hight Score
     * @param {BlockAtPublicRequestDTO} [blockAtPublicRequestDTO]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlockApiInterface
     */
    blockAtPublicRaw(requestParameters: BlockAtPublicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<BlockDTO>>;

    /**
     * Gets a block from the chain that has the given height.
     * Block at given hight Score
     */
    blockAtPublic(requestParameters: BlockAtPublicRequest, initOverrides?: RequestInit): Promise<BlockDTO>;
}

/**
 *
 */
export class BlockApi extends runtime.BaseAPI implements BlockApiInterface {
    /**
     * Gets a block from the chain that has the given height.
     * Block at given hight Score
     */
    async blockAtPublicRaw(requestParameters: BlockAtPublicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<BlockDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request(
            {
                path: `/block/at/public`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: BlockAtPublicRequestDTOToJSON(requestParameters.blockAtPublicRequestDTO),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockDTOFromJSON(jsonValue));
    }

    /**
     * Gets a block from the chain that has the given height.
     * Block at given hight Score
     */
    async blockAtPublic(requestParameters: BlockAtPublicRequest, initOverrides?: RequestInit): Promise<BlockDTO> {
        const response = await this.blockAtPublicRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
