/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockDTO, BlockDTOFromJSON, ChainHeightDTO, ChainHeightDTOFromJSON, ChainScoreDTO, ChainScoreDTOFromJSON } from '../models';
import * as runtime from '../runtime';

/**
 * ChainApi - interface
 *
 * @export
 * @interface ChainApiInterface
 */
export interface ChainApiInterface {
    /**
     * Gets the current height of the block chain.
     * @summary Chain Height
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChainApiInterface
     */
    chainHeightRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ChainHeightDTO>>;

    /**
     * Gets the current height of the block chain.
     * Chain Height
     */
    chainHeight(initOverrides?: RequestInit): Promise<ChainHeightDTO>;

    /**
     * Gets the current last block of the chain.
     * @summary Chain Last Block
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChainApiInterface
     */
    chainLastBlockRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<BlockDTO>>;

    /**
     * Gets the current last block of the chain.
     * Chain Last Block
     */
    chainLastBlock(initOverrides?: RequestInit): Promise<BlockDTO>;

    /**
     * Gets the current scroe of the block chain.
     * @summary Chain Score
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChainApiInterface
     */
    chainSocreRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ChainScoreDTO>>;

    /**
     * Gets the current scroe of the block chain.
     * Chain Score
     */
    chainSocre(initOverrides?: RequestInit): Promise<ChainScoreDTO>;
}

/**
 *
 */
export class ChainApi extends runtime.BaseAPI implements ChainApiInterface {
    /**
     * Gets the current height of the block chain.
     * Chain Height
     */
    async chainHeightRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ChainHeightDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/chain/height`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ChainHeightDTOFromJSON(jsonValue));
    }

    /**
     * Gets the current height of the block chain.
     * Chain Height
     */
    async chainHeight(initOverrides?: RequestInit): Promise<ChainHeightDTO> {
        const response = await this.chainHeightRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets the current last block of the chain.
     * Chain Last Block
     */
    async chainLastBlockRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<BlockDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/chain/last-block`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockDTOFromJSON(jsonValue));
    }

    /**
     * Gets the current last block of the chain.
     * Chain Last Block
     */
    async chainLastBlock(initOverrides?: RequestInit): Promise<BlockDTO> {
        const response = await this.chainLastBlockRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets the current scroe of the block chain.
     * Chain Score
     */
    async chainSocreRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ChainScoreDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/chain/score`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ChainScoreDTOFromJSON(jsonValue));
    }

    /**
     * Gets the current scroe of the block chain.
     * Chain Score
     */
    async chainSocre(initOverrides?: RequestInit): Promise<ChainScoreDTO> {
        const response = await this.chainSocreRaw(initOverrides);
        return await response.value();
    }
}
