/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllNodesDTO, AllNodesDTOFromJSON, NodeListDTO, NodeListDTOFromJSON } from '../models';
import * as runtime from '../runtime';

/**
 * NodeApi - interface
 *
 * @export
 * @interface NodeApiInterface
 */
export interface NodeApiInterface {
    /**
     * Gets an array of active nodes in the neighborhood that are selected for broadcasts.
     * @summary Gets an array with all the active nodes.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodeApiInterface
     */
    nodePeerListActiveRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<NodeListDTO>>;

    /**
     * Gets an array of active nodes in the neighborhood that are selected for broadcasts.
     * Gets an array with all the active nodes.
     */
    nodePeerListActive(initOverrides?: RequestInit): Promise<NodeListDTO>;

    /**
     * Gets an array of all known nodes in the neighborhood.
     * @summary Gets all the peer nodes.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodeApiInterface
     */
    nodePeerListAllRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<AllNodesDTO>>;

    /**
     * Gets an array of all known nodes in the neighborhood.
     * Gets all the peer nodes.
     */
    nodePeerListAll(initOverrides?: RequestInit): Promise<AllNodesDTO>;

    /**
     * Gets an array of all nodes with status \'active\' in the neighborhood.
     * @summary Gets an array all reachable nodes.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NodeApiInterface
     */
    nodePeerListReachableRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<NodeListDTO>>;

    /**
     * Gets an array of all nodes with status \'active\' in the neighborhood.
     * Gets an array all reachable nodes.
     */
    nodePeerListReachable(initOverrides?: RequestInit): Promise<NodeListDTO>;
}

/**
 *
 */
export class NodeApi extends runtime.BaseAPI implements NodeApiInterface {
    /**
     * Gets an array of active nodes in the neighborhood that are selected for broadcasts.
     * Gets an array with all the active nodes.
     */
    async nodePeerListActiveRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<NodeListDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/node/peer-list/active`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeListDTOFromJSON(jsonValue));
    }

    /**
     * Gets an array of active nodes in the neighborhood that are selected for broadcasts.
     * Gets an array with all the active nodes.
     */
    async nodePeerListActive(initOverrides?: RequestInit): Promise<NodeListDTO> {
        const response = await this.nodePeerListActiveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets an array of all known nodes in the neighborhood.
     * Gets all the peer nodes.
     */
    async nodePeerListAllRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<AllNodesDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/node/peer-list/all`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => AllNodesDTOFromJSON(jsonValue));
    }

    /**
     * Gets an array of all known nodes in the neighborhood.
     * Gets all the peer nodes.
     */
    async nodePeerListAll(initOverrides?: RequestInit): Promise<AllNodesDTO> {
        const response = await this.nodePeerListAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Gets an array of all nodes with status \'active\' in the neighborhood.
     * Gets an array all reachable nodes.
     */
    async nodePeerListReachableRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<NodeListDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/node/peer-list/reachable`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => NodeListDTOFromJSON(jsonValue));
    }

    /**
     * Gets an array of all nodes with status \'active\' in the neighborhood.
     * Gets an array all reachable nodes.
     */
    async nodePeerListReachable(initOverrides?: RequestInit): Promise<NodeListDTO> {
        const response = await this.nodePeerListReachableRaw(initOverrides);
        return await response.value();
    }
}
