/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NodeDTO, NodeDTOFromJSON, NodeDTOToJSON } from './';

/**
 *
 * @export
 * @interface AllNodesDTO
 */
export interface AllNodesDTO {
    /**
     *
     * @type {Array<NodeDTO>}
     * @memberof AllNodesDTO
     */
    inactive: Array<NodeDTO>;
    /**
     *
     * @type {Array<NodeDTO>}
     * @memberof AllNodesDTO
     */
    failure: Array<NodeDTO>;
    /**
     *
     * @type {Array<NodeDTO>}
     * @memberof AllNodesDTO
     */
    busy: Array<NodeDTO>;
    /**
     *
     * @type {Array<NodeDTO>}
     * @memberof AllNodesDTO
     */
    active: Array<NodeDTO>;
}

export function AllNodesDTOFromJSON(json: any): AllNodesDTO {
    return AllNodesDTOFromJSONTyped(json, false);
}

export function AllNodesDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllNodesDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        inactive: (json['inactive'] as Array<any>).map(NodeDTOFromJSON),
        failure: (json['failure'] as Array<any>).map(NodeDTOFromJSON),
        busy: (json['busy'] as Array<any>).map(NodeDTOFromJSON),
        active: (json['active'] as Array<any>).map(NodeDTOFromJSON),
    };
}

export function AllNodesDTOToJSON(value?: AllNodesDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        inactive: (value.inactive as Array<any>).map(NodeDTOToJSON),
        failure: (value.failure as Array<any>).map(NodeDTOToJSON),
        busy: (value.busy as Array<any>).map(NodeDTOToJSON),
        active: (value.active as Array<any>).map(NodeDTOToJSON),
    };
}
