/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BlockDTOPrevBlockHash,
    BlockDTOPrevBlockHashFromJSON,
    BlockDTOPrevBlockHashToJSON,
    TransactionDTO,
    TransactionDTOFromJSON,
    TransactionDTOToJSON,
} from './';

/**
 *
 * @export
 * @interface BlockDTO
 */
export interface BlockDTO {
    /**
     * The number of seconds elapsed since the creation of the nemesis block. Future timestamps are not allowed. Transaction validation detects future timestamps and returns an error in that case. Network time synchronization ensures that any NEM software component will use valid timestamps when creating transactions.
     * @type {number}
     * @memberof BlockDTO
     */
    timeStamp: number;
    /**
     * The transaction signature. The transaction signature is validated using the supplied public key in the field signer. If the signature is not valid, an error is returned from validation.
     * @type {string}
     * @memberof BlockDTO
     */
    signature: string;
    /**
     *
     * @type {BlockDTOPrevBlockHash}
     * @memberof BlockDTO
     */
    prevBlockHash: BlockDTOPrevBlockHash;
    /**
     *
     * @type {number}
     * @memberof BlockDTO
     */
    type: number;
    /**
     * List of transacitons of this block
     * @type {Array<TransactionDTO>}
     * @memberof BlockDTO
     */
    transactions: Array<TransactionDTO>;
    /**
     *
     * @type {string}
     * @memberof BlockDTO
     */
    signer: string;
    /**
     *
     * @type {number}
     * @memberof BlockDTO
     */
    height: number;
}

export function BlockDTOFromJSON(json: any): BlockDTO {
    return BlockDTOFromJSONTyped(json, false);
}

export function BlockDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        timeStamp: json['timeStamp'],
        signature: json['signature'],
        prevBlockHash: BlockDTOPrevBlockHashFromJSON(json['prevBlockHash']),
        type: json['type'],
        transactions: (json['transactions'] as Array<any>).map(TransactionDTOFromJSON),
        signer: json['signer'],
        height: json['height'],
    };
}

export function BlockDTOToJSON(value?: BlockDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        timeStamp: value.timeStamp,
        signature: value.signature,
        prevBlockHash: BlockDTOPrevBlockHashToJSON(value.prevBlockHash),
        type: value.type,
        transactions: (value.transactions as Array<any>).map(TransactionDTOToJSON),
        signer: value.signer,
        height: value.height,
    };
}
