/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 *
 * @export
 * @interface ModelErrorDTO
 */
export interface ModelErrorDTO {
    /**
     * The number of seconds elapsed since the creation of the nemesis block. Future timestamps are not allowed. Transaction validation detects future timestamps and returns an error in that case. Network time synchronization ensures that any NEM software component will use valid timestamps when creating transactions.
     * @type {number}
     * @memberof ModelErrorDTO
     */
    timeStamp: number;
    /**
     *
     * @type {string}
     * @memberof ModelErrorDTO
     */
    error: string;
    /**
     *
     * @type {string}
     * @memberof ModelErrorDTO
     */
    message?: string;
    /**
     *
     * @type {number}
     * @memberof ModelErrorDTO
     */
    status: number;
}

export function ModelErrorDTOFromJSON(json: any): ModelErrorDTO {
    return ModelErrorDTOFromJSONTyped(json, false);
}

export function ModelErrorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelErrorDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        timeStamp: json['timeStamp'],
        error: json['error'],
        message: !exists(json, 'message') ? undefined : json['message'],
        status: json['status'],
    };
}

export function ModelErrorDTOToJSON(value?: ModelErrorDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        timeStamp: value.timeStamp,
        error: value.error,
        message: value.message,
        status: value.status,
    };
}
