/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NodeDTO, NodeDTOFromJSON, NodeDTOToJSON } from './';

/**
 *
 * @export
 * @interface NodeListDTO
 */
export interface NodeListDTO {
    /**
     *
     * @type {Array<NodeDTO>}
     * @memberof NodeListDTO
     */
    data: Array<NodeDTO>;
}

export function NodeListDTOFromJSON(json: any): NodeListDTO {
    return NodeListDTOFromJSONTyped(json, false);
}

export function NodeListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeListDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        data: (json['data'] as Array<any>).map(NodeDTOFromJSON),
    };
}

export function NodeListDTOToJSON(value?: NodeListDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        data: (value.data as Array<any>).map(NodeDTOToJSON),
    };
}
