/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 *
 * @export
 * @interface NodeDTOMetaData
 */
export interface NodeDTOMetaData {
    /**
     *
     * @type {number}
     * @memberof NodeDTOMetaData
     */
    features: number;
    /**
     *
     * @type {string}
     * @memberof NodeDTOMetaData
     */
    application?: string;
    /**
     *
     * @type {number}
     * @memberof NodeDTOMetaData
     */
    networkId: number;
    /**
     *
     * @type {string}
     * @memberof NodeDTOMetaData
     */
    version: string;
    /**
     *
     * @type {string}
     * @memberof NodeDTOMetaData
     */
    platform: string;
}

export function NodeDTOMetaDataFromJSON(json: any): NodeDTOMetaData {
    return NodeDTOMetaDataFromJSONTyped(json, false);
}

export function NodeDTOMetaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeDTOMetaData {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        features: json['features'],
        application: !exists(json, 'application') ? undefined : json['application'],
        networkId: json['networkId'],
        version: json['version'],
        platform: json['platform'],
    };
}

export function NodeDTOMetaDataToJSON(value?: NodeDTOMetaData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        features: value.features,
        application: value.application,
        networkId: value.networkId,
        version: value.version,
        platform: value.platform,
    };
}
