/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NodeDTOEndpoint,
    NodeDTOEndpointFromJSON,
    NodeDTOEndpointToJSON,
    NodeDTOIdentity,
    NodeDTOIdentityFromJSON,
    NodeDTOIdentityToJSON,
    NodeDTOMetaData,
    NodeDTOMetaDataFromJSON,
    NodeDTOMetaDataToJSON,
} from './';

/**
 *
 * @export
 * @interface NodeDTO
 */
export interface NodeDTO {
    /**
     *
     * @type {NodeDTOMetaData}
     * @memberof NodeDTO
     */
    metaData: NodeDTOMetaData;
    /**
     *
     * @type {NodeDTOEndpoint}
     * @memberof NodeDTO
     */
    endpoint: NodeDTOEndpoint;
    /**
     *
     * @type {NodeDTOIdentity}
     * @memberof NodeDTO
     */
    identity: NodeDTOIdentity;
}

export function NodeDTOFromJSON(json: any): NodeDTO {
    return NodeDTOFromJSONTyped(json, false);
}

export function NodeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        metaData: NodeDTOMetaDataFromJSON(json['metaData']),
        endpoint: NodeDTOEndpointFromJSON(json['endpoint']),
        identity: NodeDTOIdentityFromJSON(json['identity']),
    };
}

export function NodeDTOToJSON(value?: NodeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        metaData: NodeDTOMetaDataToJSON(value.metaData),
        endpoint: NodeDTOEndpointToJSON(value.endpoint),
        identity: NodeDTOIdentityToJSON(value.identity),
    };
}
