/* tslint:disable */
/* eslint-disable */
/**
 * NEM Rest Endpoints
 * OpenAPI Specification of NEM nodes.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import { MessageDTO, MessageDTOFromJSON, MessageDTOToJSON } from './';

/**
 *
 * @export
 * @interface TransactionDTO
 */
export interface TransactionDTO {
    /**
     * The number of seconds elapsed since the creation of the nemesis block. Future timestamps are not allowed. Transaction validation detects future timestamps and returns an error in that case. Network time synchronization ensures that any NEM software component will use valid timestamps when creating transactions.
     * @type {number}
     * @memberof TransactionDTO
     */
    timeStamp: number;
    /**
     *
     * @type {number}
     * @memberof TransactionDTO
     */
    mode?: number;
    /**
     * The transaction signature. The transaction signature is validated using the supplied public key in the field signer. If the signature is not valid, an error is returned from validation.
     * @type {string}
     * @memberof TransactionDTO
     */
    signature: string;
    /**
     *
     * @type {number}
     * @memberof TransactionDTO
     */
    fee: number;
    /**
     *
     * @type {number}
     * @memberof TransactionDTO
     */
    deadline: number;
    /**
     *
     * @type {number}
     * @memberof TransactionDTO
     */
    type: number;
    /**
     *
     * @type {string}
     * @memberof TransactionDTO
     */
    remoteAccount?: string;
    /**
     *
     * @type {string}
     * @memberof TransactionDTO
     */
    signer: string;
    /**
     *
     * @type {number}
     * @memberof TransactionDTO
     */
    version: number;
    /**
     *
     * @type {string}
     * @memberof TransactionDTO
     */
    recipient?: string;
    /**
     *
     * @type {MessageDTO}
     * @memberof TransactionDTO
     */
    message?: MessageDTO;
}

export function TransactionDTOFromJSON(json: any): TransactionDTO {
    return TransactionDTOFromJSONTyped(json, false);
}

export function TransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        timeStamp: json['timeStamp'],
        mode: !exists(json, 'mode') ? undefined : json['mode'],
        signature: json['signature'],
        fee: json['fee'],
        deadline: json['deadline'],
        type: json['type'],
        remoteAccount: !exists(json, 'remoteAccount') ? undefined : json['remoteAccount'],
        signer: json['signer'],
        version: json['version'],
        recipient: !exists(json, 'recipient') ? undefined : json['recipient'],
        message: !exists(json, 'message') ? undefined : MessageDTOFromJSON(json['message']),
    };
}

export function TransactionDTOToJSON(value?: TransactionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        timeStamp: value.timeStamp,
        mode: value.mode,
        signature: value.signature,
        fee: value.fee,
        deadline: value.deadline,
        type: value.type,
        remoteAccount: value.remoteAccount,
        signer: value.signer,
        version: value.version,
        recipient: value.recipient,
        message: MessageDTOToJSON(value.message),
    };
}
